[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "1779063631", # Zeus Enhanced
    "463939057", # ACE3
    "3499977893", # Advanced Developer Tools
]
mission = "BasicMission.VR" # Mission to launch directly into the editor with   
parameters = [
    "-noPause",
]
